cinema/auth.py
from flask import Blueprint, render_template, url_for, request, session, redirect, flash
import psycopg2
import psycopg2.extras
from werkzeug.security import generate_password_hash, check_password_hash
from .config import db_name, user, password, host

auth = Blueprint('auth', __name__)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    session.permanent = False
    session.modified = True
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    if request.method == "POST" and 'login' in request.form:
        user_password = request.form['user_password']
        user_password1 = request.form['user_password1']
        user_name = request.form['user_name']
        login = request.form['login']
        date_of_birth = request.form['date']

        _hashed_password = generate_password_hash(user_password)
        print(_hashed_password)

        cursor.execute('SELECT * FROM cinema_user WHERE login = %s', (login,))
        account = cursor.fetchone()
        print(account)

        # If account exists show error and validation checks
        if account:
            flash('Аккаунт уже существует')
        elif not user_password:
            flash('Заполните все формы!')
        elif user_password != user_password1:
            flash('Пароли не совпадают')
        else:

            # Account doesn't exist and the form data is valid, now insert new account into users table
            cursor.execute("INSERT INTO cinema_user (login, user_password, user_name, date_of_birth) VALUES (%s,%s,%s,%s)",
                           (login, _hashed_password, user_name, date_of_birth))
            conn.commit()
            flash('Вы успешно зарегистрировались!')

    elif request.method == 'POST':

        # Form is empty... (no POST data)
        flash('Заполните все формы!')

        # Show registration form with message (if any)
    return render_template('register.html')


@auth.route('/login/', methods=['GET', 'POST'])
def login():
    session.permanent = False

    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    # user submitted form
    if request.method == 'POST' and 'login' in request.form and 'user_password' in request.form:
        login = request.form['login']
        user_password = request.form['user_password']

        # check if exist in database
        cursor.execute('SELECT * FROM cinema_user WHERE login = %s', (login,))
        account = cursor.fetchone()
        print(account)

        if account:
            password_rs = account['user_password']
            print(password_rs)

            if check_password_hash(password_rs, user_password):
                session['logged_in'] = True
                session.modified = True
                print(session.get('logged_in'))
                session['login'] = account['login']
                print(session.get('login'))
                adm = account['isadmin']
                print(adm)
                user_name = account['user_name']
                if adm:
                    session['isAdmin'] = True
                    flash('Вы успешно вошли в аккаунт, Админ! ')
                    return redirect(url_for('view.admin'))
                else:
                    session['isAdmin'] = False
                    flash('Вы успешно вошли в аккаунт')
                    return redirect(url_for('view.home'))

            else:
                flash('Неправильный пароль')

        else:
            flash('Неправильный логин или пароль')

    return render_template('login.html'), session


@auth.route('/logout')
def logout():
    session.pop('logged_in', None)
    session.pop('isAdmin', None)
    session.pop('seance_id', None)
    session.pop('ticket_cost', None)
    session.pop('user_id', None)
    session.pop('title', None)
    session.pop('date', None)
    session.pop('time', None)
    session.pop('hall', None)
    flash('Вы успешно вышли из аккаунта')
    return redirect(url_for('view.home'))

cinema/views.py
from flask import Blueprint, render_template, url_for, request, session, redirect, flash
import psycopg2
import psycopg2.extras
from .config import db_name, user, password, host

view = Blueprint('view', __name__)


@view.route('/', methods=['GET', 'POST'])
def home():
    return render_template('home.html')


@view.route('/profile')
def profile():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    # условие проверки авторизации пользователя
    if 'logged_in' in session:
        cursor.execute('SELECT * FROM cinema_user WHERE login = %s',  [session['login']])
        account = cursor.fetchone()
        user_id = account[0]
        print(user_id)

        cursor.execute('SELECT film.title, seance.seance_date, seance.seance_time, seance.hall, '
                       'ticket.row, ticket.place, ticket.ticket_cost FROM ticket INNER JOIN seance '
                       'ON ticket.seance_id = seance.id INNER JOIN film ON seance.film_id = film.id'
                       ' WHERE ticket.user_id =%s', (user_id,))
        ticket = cursor.fetchall()
        ticket_len = len(ticket)

        return render_template('profile.html', account=account, ticket=ticket, ticket_len=ticket_len)
    # функция перенаправления
    return redirect(url_for('view.login'))


@view.route('/afisha', methods=['GET', 'POST'])
def afisha():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute('SELECT title, release_date, countries_of_origin, genres, '
                   'age_limit, runtime, director, summary FROM film')
    film = cursor.fetchall()
    # Вычисление длинны массива
    film_len = len(film)

    return render_template('afisha.html', film=film, film_len=film_len)


@view.route('/about_cinema', methods=['GET', 'POST'])
def cinema():
    return render_template('cinema.html')


@view.route('/hall')
def hall():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute('SELECT * FROM hall')
    hall_inf = cursor.fetchall()
    hall_len = len(hall_inf)

    return render_template('hall.html', hall_inf=hall_inf, hall_len=hall_len)


@view.route('/akzii')
def akzii():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute('SELECT * FROM akzii')
    akzii = cursor.fetchall()
    akzii_len = len(akzii)

    return render_template('akzii.html', akzii=akzii, akzii_len=akzii_len)


@view.route('/add_akzii', methods=['GET', 'POST'])
def add_akzii():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    if request.method == "POST":
        name = request.form['name']
        discription = request.form['discription']

        cursor.execute(
            "INSERT INTO akzii (name, discription) VALUES (%s,%s)", (name, discription, ))
        conn.commit()
        flash('Информация об акции добавлена')

    return render_template('add_akzii.html')


@view.route('/del_akzii', methods=['GET', 'POST'])
def del_akzii():
    if 'logged_in' not in session:
        redirect(url_for('home'))

    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute("SELECT name FROM akzii")
    akzii = cursor.fetchall()
    hakzii_len = len(akzii)
    akzii_dict = {}
    for i in range(hakzii_len):
        akzii_dict[i + 1] = akzii[i][0]

    if request.method == 'POST':
        if request.form['option_delete'] == '0':
            pass
        else:
            option_delete = request.form['option_delete']
            option_delete_value = akzii_dict[int(option_delete)]
            cursor.execute("DELETE FROM akzii WHERE name =%s", (option_delete_value,))
            conn.commit()

            flash('Акция удалена')

        return redirect(url_for('view.del_akzii'))
    return render_template("del_akzii.html", akzii_dict=akzii_dict)


@view.route('/admin', methods=['GET', 'POST'])
def admin():
    return render_template('admin.html')


@view.route('/add_film', methods=['GET', 'POST'])
def add_film():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute("SELECT genre_name FROM genre")
    genre_name = cursor.fetchall()
    genre_name_len = len(genre_name)
    genre_name_dict = {}
    for i in range(genre_name_len):
        genre_name_dict[i+1] = genre_name[i][0]

    if request.method == "POST":
        film_id = request.form['id']
        title = request.form['title']
        release_date = request.form['release_date']
        countries_of_origin = request.form['countries_of_origin']
        genres = request.form['option_genre']
        age_limit = request.form['age_limit']
        runtime = request.form['runtime']
        director = request.form['director']
        summary = request.form['summary']

        cursor.execute('SELECT genre_name FROM genre WHERE id = %s', (genres,))
        film_genre = cursor.fetchone()

        cursor.execute('SELECT * FROM film WHERE id = %s', (film_id,))
        film = cursor.fetchone()
        print(film)

        if film:
            flash('Такой фильм уже есть в базе')
        else:
            cursor.execute(
                "INSERT INTO film (id, title, release_date, countries_of_origin, genres, age_limit, runtime, director, "
                "summary) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (film_id, title, release_date, countries_of_origin, film_genre, age_limit, runtime, director, summary))
            conn.commit()
            cursor.execute(
                "INSERT INTO film_genre (film_id, genre_id) VALUES (%s,%s)",
                (int(film_id), int(genres)))
            conn.commit()
            flash('Фильм добавлен')

    return render_template('add_film.html', genre_name_dict=genre_name_dict)


@view.route('/del_film', methods=['GET', 'POST'])
def del_film():
    if 'logged_in' not in session:
        redirect(url_for('home'))

    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute("SELECT title FROM film")
    film_title = cursor.fetchall()
    film_len = len(film_title)
    film_dict = {}
    for i in range(film_len):
        film_dict[i + 1] = film_title[i][0]

    if request.method == 'POST':
        if request.form['option_delete'] == '0':
            pass
        else:
            option_delete = request.form['option_delete']
            option_delete_value = film_dict[int(option_delete)]
            cursor.execute("SELECT id FROM film WHERE title =%s", (option_delete_value,))
            film_id = cursor.fetchall()
            cursor.execute("SELECT film_id FROM seance WHERE film_id =%s", film_id[0])
            seance = cursor.fetchall()

            if seance:
                flash('Нельзя удалить фильм, пока он в прокате')
            else:
                cursor.execute("DELETE FROM film_genre WHERE film_id =%s", film_id[0])
                conn.commit()
                cursor.execute("DELETE FROM film WHERE title =%s", (option_delete_value,))
                conn.commit()

                flash('Фильм удален')

            return redirect(url_for('view.del_film'))
    return render_template("del_film.html", film_dict=film_dict)


@view.route('/del_hall', methods=['GET', 'POST'])
def del_hall():
    if 'logged_in' not in session:
        redirect(url_for('home'))

    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    cursor.execute("SELECT id FROM hall")
    hall_id = cursor.fetchall()
    hall_id_len = len(hall_id)
    hall_id_dict = {}
    for i in range(hall_id_len):
        hall_id_dict[i + 1] = hall_id[i][0]

    if request.method == 'POST':
        if request.form['option_delete'] == '0':
            pass
        else:
            option_delete = request.form['option_delete']
            option_delete_value = hall_id_dict[int(option_delete)]

            cursor.execute("SELECT hall FROM seance WHERE hall =%s", (option_delete_value,))
            hall = cursor.fetchall()

            if hall:
                flash('Нельзя удалить зал, пока там идут сеансы')
            else:
                cursor.execute("DELETE FROM hall WHERE id =%s", (option_delete_value,))
                conn.commit()

                flash('Зал удален')

            return redirect(url_for('view.del_hall'))
    return render_template("del_hall.html", hall_id_dict=hall_id_dict)


@view.route('/add_hall', methods=['GET', 'POST'])
def add_hall():
    conn = psycopg2.connect(dbname=db_name, user=user, password=password, host=host)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    if request.method == "POST":
        hall_id = request.form['id']
        place_count = request.form['place_count']
        row_num = request.form['row_num']
        place_num = request.form['place_num']

        cursor.execute('SELECT * FROM hall WHERE id = %s', (hall_id,))
        hall = cursor.fetchone()
        print(hall)

        if hall:
            flash('Информация про этот зал уже есть в базе')
        else:
            cursor.execute(
                "INSERT INTO hall (id, place_count, row_num, place_num) VALUES (%s,%s,%s,%s)",
                (hall_id, place_count, row_num, place_num))
            conn.commit()
            flash('Информация про этот зал добавлена')

    return render_template('add_hall.html')

cinema/templates/add_akzii.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавление зала</title>
      <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

</head>
<body>

   <nav class="navbar navbar-expand-lg navbar-blue" style="background-color:#e3f2fd;">
   <div class="container">
      <header class="d-flex justify-content-center py-3">
         <div class="navbar-nav">
          {% if session['isAdmin'] %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.admin') }}">Страница администратора</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.profile') }}">Профиль</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.logout') }}">Выход</a>
          {% elif session['logged_in'] %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.profile') }}">Профиль</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.logout') }}">Выход</a>
          {% else %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.register') }}">Регистрация</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.login') }}">Вход</a>
          {% endif %}
          </div>
      </header>
    </div>
    </nav><br>

   {% if session['isAdmin'] %}
    <h2 style=position:absolute;left:8%;>Добавление информации об акциях</h2><br><br>

   {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul style=position:absolute;left:8%;>
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}

    <br><br>
    <form class="form-add_hall" action="{{ url_for('view.add_akzii') }}" method="post" style=position:absolute;left:8%;>
        <input type="text" class="form-add_hall" name="name" placeholder="Название" id="name" required>
        <label>Название</label><br>
        <textarea cols="45" class = "form-add_film" name="discription" placeholder="Описание" id="discription" required> </textarea>
        <label>Описание</label><br>
        <input type="submit" value="Добавить" class="form-submit" name=""><br>
        <br>

        <a href="{{ url_for('view.add_akzii') }}">Страница админа</a>
    </form>
    {% else %}
    <p>У вас нет доступа к этой странице.</p>
    {% endif %}

</body>
</html>

cinema/templates/add_film.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавление фильма</title>
      <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

</head>
<body>

   <nav class="navbar navbar-expand-lg navbar-blue" style="background-color:#e3f2fd;">
   <div class="container">
      <header class="d-flex justify-content-center py-3">
         <div class="navbar-nav">
         {% if session['isAdmin'] %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.admin') }}">Страница администратора</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.profile') }}">Профиль</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.logout') }}">Выход</a>
          {% elif session['logged_in'] %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.profile') }}">Профиль</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.logout') }}">Выход</a>
          {% else %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.register') }}">Регистрация</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.login') }}">Вход</a>
          {% endif %}
          </div>
      </header>
    </div>
    </nav><br>

   {% if session['isAdmin'] %}
    <h2 style=position:absolute;left:8%;>Добавление фильма</h2><br><br>

       {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul style=position:absolute;left:8%;>
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}

    <br><br>
    <form class="form-add_film" action="{{ url_for('view.add_film') }}" method="post" style=position:absolute;left:8%;>
        <input type="text" class="form-add_film" name="id" placeholder="ПУ" id="id" required>
        <label>ПУ</label><br>
        <input type="text" class = "form-add_film" name="title" placeholder="Название" id="title" required>
        <label>Название</label><br>
<!--        <input type="text" class = "form-add_film" name="release_date" placeholder="Дата выхода" id="release_date" required>-->
        <input type="date"  class="form-date" id="release_date" name="release_date" style=width:190px;/>
        <label>Дата выхода</label><br>
        <input type="text" class = "form-add_film" name="countries_of_origin" placeholder="Страна выхода" id="countries_of_origin" required>
        <label>Страна выхода</label><br>
        <select style=width:190px; name="option_genre">
        <option value="0">Жанр</option>
        {% for key, value in genre_name_dict.items() %}
        <option value="{{ key }}">{{ value }}</option>
        {% endfor %}
        </select>

<!--        <input type="text" class = "form-add_film" name="genres" placeholder="Жанр" id="genres" required>-->
        <label>Жанр</label><br>
        <input type="text" class = "form-add_film" name="age_limit" placeholder="Возрастное ограничение" id="age_limit" required>
        <label>Возрастное ограничение</label><br>
        <input type="text" class = "form-add_film" name="runtime" placeholder="Время" id="runtime" required>
        <label>Время</label><br>
        <input type="text" class = "form-add_film" name="director" placeholder="Режиссер" id="director" required>
        <label>Режиссер</label><br>
        <textarea cols="45" class = "form-add_film" name="summary" placeholder="Описание" id="summary" required> </textarea>
        <label>Описание</label><br>
        <br>
        <input type="submit" value="Добавить" class="form-submit" name=""><br>
        <br>


        <a href="{{ url_for('view.admin') }}">Страница админа</a>
    </form>
    {% else %}
    <p>У вас нет доступа к этой странице.</p>
    {% endif %}

</body>
</html>

cinema/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Админ</title>
  <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
</head>
<body link="#2f4f4f" vlink="#000000" alink="#191970" bgcolor="black">


   <nav class="navbar navbar-expand-lg navbar-blue" style="background-color:#e3f2fd;">
   <div class="container">
      <header class="d-flex justify-content-center py-3">
         <div class="navbar-nav">
         {% if session['isAdmin'] %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.admin') }}">Страница администратора</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.profile') }}">Профиль</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.logout') }}">Выход</a>
          {% elif session['logged_in'] %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.profile') }}">Профиль</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.logout') }}">Выход</a>
          {% else %}
          <a class="nav-item nav-link"  href="{{ url_for('view.home') }}">Главная</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.afisha') }}">Афиша</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.seance') }}">Расписание</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.add_ticket') }}">Купить билет</a>
          <a class="nav-item nav-link"  href="{{ url_for('view.cinema') }}">О кинотеатре</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.register') }}">Регистрация</a>
          <a class="nav-item nav-link"  href="{{ url_for('auth.login') }}">Вход</a>
          {% endif %}
          </div>

      </header>
    </div>

    </nav><br>

<center><h1 style="text-transform:uppercase">Кинотеатр "Хогвартс"</h1>
    {% if session['isAdmin'] %}
    <p>Здесь вы имеете возможность добавлять, просматривать, редактировать и удалять данные о фильмах, расписании и акциях</p>
     <a href="{{ url_for('view.add_film') }}">Добавить фильм</a><br>
     <a href="{{ url_for('view.del_film') }}">Удалить фильм</a><br>
     <a href="{{ url_for('view.add_seance') }}">Добавить сеанс</a><br>
     <a href="{{ url_for('view.del_seance') }}">Удалить сеанс</a><br>
     <a href="{{ url_for('view.add_hall') }}">Добавить зал</a><br>
     <a href="{{ url_for('view.del_hall') }}">Удалить зал</a><br>
     <a href="{{ url_for('view.add_akzii') }}">Добавить информацию об акциях</a><br>
     <a href="{{ url_for('view.del_akzii') }}">Удалить информацию об акциях</a>
    {% else %}
    <p>У вас нет доступа к этой странице.</p>
    {% endif %}

    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul>
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}

</center>

</body>
</html>